### PR TITLE
fix(packages): correctly mark peer dependency

### LINKED ISSUE #3428: react-instantsearch-dom@npm:6.23.3 doesn't provide algoliasearch, requested by algoliasearch-helper
## 🐛 Bug description

Running `yarn install` shows me two warnings.
```
➤ YN0002: │ react-instantsearch-dom@npm:6.23.3 [a2c17] doesn't provide algoliasearch (pd384a), requested by algoliasearch-helper
➤ YN0002: │ react-instantsearch-dom@npm:6.23.3 [a2c17] doesn't provide algoliasearch (pe0e9b), requested by react-instantsearch-core
```

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**
1. yarn set version stable
2. yarn add react-instantsearch-dom
3. yarn add algoliasearch
4. yarn install
5. There it should show you the warning

You can also try [my small example app](https://github.com/joker-777/test_app).

## 💭 Expected behavior

That it doesn't show any warnings. Either `react-instantsearch-dom` has to satisfy the `peer-dependency` of `algoliasearch-helper` and `react-instantsearch-core` or there is a way of deferring peer dependencies.

## 🖥 Screenshots

Screenshot_20220411_133148

## Environment

- OS: Linux arch 5.16.8-arch1-1
- Version: 6.23.3

### PR DESCRIPTION
**Pull request by Haroenv**
**Summary**

Transitively the peerDependency on algoliasearch is already required through algoliasearch-helper, and it's pretty much required for types too.

This won't add new errors, as the peerDependency is already present.

fixes #3428

**Result**

No errors when installing `yarn add react-instantsearch-dom algoliasearch` using Yarn 3

### CODE REVIEW

File: packages/react-instantsearch-core/src/types/algoliasearch.ts [hunk 1]
```diff
@@ -1,16 +1,15 @@
 // Custom types to support both algoliasearch
 // `v3` and algoliasearch `v4` clients.
 
-import type algoliasearch from 'algoliasearch';
-import type {
-  // @ts-ignore
-  Response as SearchResponseV3,
-} from 'algoliasearch';
+import type algoliasearch from 'algoliasearch/lite';
+import type * as AlgoliaSearch from 'algoliasearch/lite';
```
Comment (FabienMotte) [inline packages/react-instantsearch-core/src/types/algoliasearch.ts:5]:
```suggestion
import type algoliasearch, { Response as AlgoliaSearchResponse } from 'algoliasearch/lite';
```
Can't we merge this two imports?

**Review by FabienMotte — COMMENTED** [review]
Nice! 👏  I just left one comment/question

**Review by dhayab — APPROVED** [review]

File: packages/react-instantsearch-core/src/types/algoliasearch.ts (hunk 1 above)
Comment (FabienMotte) [reply packages/react-instantsearch-core/src/types/algoliasearch.ts:5]: Got it, thanks!
