### PR TITLE
fix(GoogleMapsLoader): inline the import to scriptjs

### LINKED ISSUE #1425: Reference Error :
**Bug: What is the current behavior?**

After `npm i react-instantsearch-dom-maps`, and importing `import { GoogleMapsLoader, GeoSearch, Control, Marker } from 'react-instantsearch-dom-maps';` I have an error : 

```
ReferenceError: document is not defined
W20180710-18:37:06.608(2)? (STDERR)     at /Users/sabativi/playground/pup/node_modules/scriptjs/dist/script.js:12:13
W20180710-18:37:06.608(2)? (STDERR)     at doc (/Users/sabativi/playground/pup/node_modules/scriptjs/dist/script.js:8:72)
W20180710-18:37:06.608(2)? (STDERR)     at Object.<anonymous> (/Users/sabativi/playground/pup/node_modules/scriptjs/dist/script.js:11:3)
W20180710-18:37:06.609(2)? (STDERR)     at Module._compile (module.js:652:30)
W20180710-18:37:06.609(2)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20180710-18:37:06.609(2)? (STDERR)     at Module.load (module.js:565:32)
W20180710-18:37:06.609(2)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20180710-18:37:06.609(2)? (STDERR)     at Function.Module._load (module.js:497:3)
W20180710-18:37:06.609(2)? (STDERR)     at Module.require (module.js:596:17)
W20180710-18:37:06.610(2)? (STDERR)     at require (internal/module.js:11:18)
W20180710-18:37:06.610(2)? (STDERR)     at Object.<anonymous> (/Users/sabativi/playground/pup/node_modules/react-instantsearch-dom-maps/dist/cjs/GoogleMapsLoader.js:15:17)
```

I am using meteor, but I am pretty certain this is not related.

Maybe this is due to being in an SSR environment ?

### PR DESCRIPTION
**Pull request by samouss**
**Summary**

Fix #1425 

With the current implementation of `GoogleMapsLoader` we use a top level import for `scriptjs` (the lib responsible for fetching external scripts Google Maps in our case). But this lib rely on a browser environment, it means that it throws an error with a SSR application.

To fix this issue we use a dynamic `import` syntax under `componentDidMount`. The script will be only executed on the browser (since `didMount` is not executed on the server). Note that we do not use `import` for code splitting here but only for being able to generate CJS, ESM and UMD files from one source. A regular `require` expression is not handled by Rollup.

### CODE REVIEW

File: packages/react-instantsearch-dom-maps/src/GoogleMapsLoader.js [hunk 1]
```diff
@@ -20,16 +19,21 @@ class GoogleMapsLoader extends Component {
...
-    injectScript(endpointWithCredentials, () => {
-      if (!this.isUnmounting) {
-        this.setState(() => ({
-          google: window.google,
-        }));
-      }
+    // Inline the import to avoid to run the module on the server (rely on `document`)
+    // Under the hood we use `dynamic-import-node` to transpile the `import` to `require`
+    // see: https://github.com/algolia/react-instantsearch/issues/1425
+    return import('scriptjs').then(script => {
```
Comment (Haroenv) [inline packages/react-instantsearch-dom-maps/src/GoogleMapsLoader.js]: `then(({default: script}) =>` could be readable too
