### PR TITLE
fix(ssr): remove second instance of "query" in the response "params" for SSR

### LINKED ISSUE #2940: Hydration of search client uses `query` from response instead of `request`
**Describe the bug 🐛**

This isn't usually a problem, except when a query rule changes the query (e.g. `voltaren` to `voltaren®`). This causes the cache to be missed & a request on the frontend to me made

I'd still need to check this, but I think this is only relevant for combining with `algoliasearch@4`

**To Reproduce 🔍**

1. go to an index which has an edited query (e.g. latency/instant_search for "edit_me")
2. enter that query
3. reload
4. see a query was done frontend, while it shouldn't be

This can be checked in the official next demo: https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/next

**Expected behavior 💭**

No query should be done, even if the query done by the user doesn't match up with the query in the response / from the engine

**Screenshots 🖥**

Screenshot 2020-06-15 at 17 39 23

Screenshot 2020-06-15 at 17 39 10

**Additional context**

Relevant code is:

https://github.com/algolia/react-instantsearch/blob/7e883df4b39144efe7da9d2a713658075d337028/packages/react-instantsearch-core/src/core/createInstantSearchManager.js#L322-L474

### PR DESCRIPTION
**Pull request by Haroenv**
**Summary**

We use the `params` of the response given by the Algolia query to craft a cache key for the query done by server-side rendering. However, when the engine has e.g. a query rule which edits the query, this `params` won't be the same as the one actually queried. It will have `query=original...&query=edited`, which means that we should remove the second instance of the query to make the cache not miss

**Result**

When rendering a query which is edited by a query rule, no query gets done frontend. This can be tested by the query `edit_me` on the `instant_search` index.

closes #2941
fixes #2940

### CODE REVIEW

File: packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js [hunk 1]
```diff
@@ -13,11 +13,14 @@ import { findResultsState } from '../createInstantSearchServer';
 Enzyme.configure({ adapter: new Adapter() });
 
 describe('findResultsState', () => {
-  const createSearchClient = () => ({
+  const createSearchClient = responseParams => ({
```
Comment (francoischalifour) [inline packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js:16]: Having a signature like the following would make it easier to understand:

```js
createSearchClient({ transformResponseParams } = {})
```

File: packages/react-instantsearch-dom/src/core/createInstantSearchServer.js [hunk 2]
```diff
@@ -59,9 +59,36 @@ const getSearchParameters = (indexName, searchParameters) => {
...
+/**
+ * The engine can return params: "query=xxx&query=yyy" if e.g. a query rule modifies it.
+ * This however will cause us to miss the cache hydration, so we make sure to keep
+ * only the first query (always the one from the parameters).
+ */
+function removeDuplicateQuery(params) {
+  let previousIndex = undefined;
+  const queryParamRegex = /&?query=[^&]*/g;
+  return params.replace(queryParamRegex, function replacer(match, offset) {
+    if (previousIndex !== undefined && offset > previousIndex) {
```
Comment (eunjae-lee) [inline packages/react-instantsearch-dom/src/core/createInstantSearchServer.js:71]: Can `offset > previousIndex` be false when `previousIndex !== undefined`?

Comment (Haroenv) [reply packages/react-instantsearch-dom/src/core/createInstantSearchServer.js:71]: if there's three instances of `query` that would be possible, so I left that condition to be sure

Comment (eunjae-lee) [reply packages/react-instantsearch-dom/src/core/createInstantSearchServer.js:71]: When you meet the first instance of `query`, `previousIndex` gets assigned (no longer undefined). After that, no matter how many more instances of `query` occurs, we can just return an empty string, IIUC.
Meaning, we can have just a boolean instead of `previousIndex` to store the offset.

Comment (Haroenv) [reply packages/react-instantsearch-dom/src/core/createInstantSearchServer.js]: good call, fixed
