### PR TITLE
fix(core): fix maximum call stack size exceeded

### LINKED ISSUE #2912: Maximum call stack size exceeded. Related to cache ?
**Describe the bug 🐛**

I got a 500 from SSR response. In my log I get `RangeError: Maximum call stack size exceeded`

**To Reproduce 🔍**
 
Infortunately, I have only this problem on production, not on staging or local.

If I restart my instance, everything back to normal. My memory was around 25%, I have a total o 2040 mo for my instance.

So I assume it's a problem on Algolia's cache.

**Environment:**

Next JS 9.3.4, Algolia javascript 4.1, ReactInstantSearch 6.4.0.

Never had the problem with Algolia 3.35.1 and ReactInstanceSearch 6.3.0

**Additional context**

```
14:30:24
RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
```

### PR DESCRIPTION
**Pull request by nunomaduro**
Fixes #2912 

This pull request addresses a bug that is impacting all the customers using React Instantsearch v6.4 with Algoliasearch v4, and having high traffic in their applications.

**Problem**: Internally, on the function `hydrateSearchClient`, the `search` method on the client was being overridden in every request by the previous version of it, eventually causing maximum call stack size exceeded.

**Solution**: This pull request adds a flag to the given client so his search doesn't get override more than once. As the cache as already hydrated before.

**Feedback about this**: The cache hydration system only works when customers are using ` responsesCache: createInMemoryCache(),`. Not sure if that is clear on the docs or for us.

Going to test this pull request a little bit in my side now, meanwhile, you guys can validate this.

Note: Also updated the demo server side rendering re-use the some client between requests.

### CODE REVIEW

**Comment by Haroenv** [comment]
This fix looks smart to me. In the future this could be fixed with https://github.com/algolia/algoliasearch-client-javascript/pull/1145 where we don't have to override the search method

File: packages/react-instantsearch-core/src/core/createInstantSearchManager.js [hunk 1]
```diff
@@ -342,6 +342,8 @@ export default function createInstantSearchManager({
     // to populate it on a custom key and override the `search` method to
     // search on it first.
     if (client.transporter) {
+      client._cacheHydrated = true;
```
Comment (Haroenv) [inline packages/react-instantsearch-core/src/core/createInstantSearchManager.js:345]: let's maybe add a test where we serialise twice?

File: packages/react-instantsearch-core/src/core/createInstantSearchManager.js [hunk 2]
```diff
@@ -328,7 +328,7 @@ export default function createInstantSearchManager({
     // - Algoliasearch API Client < v4 with cache disabled
     // - Third party clients (detected by the `addAlgoliaAgent` function missing)
     if (
-      !client.transporter &&
+      (!client.transporter || client._cacheHydrated) &&
```
Comment (francoischalifour) [inline packages/react-instantsearch-core/src/core/createInstantSearchManager.js:331]: Don't we want to bypass all the other checks if `client._cacheHydrated` is `true`?

**Comment by Haroenv** [comment]
I prefer a variable on the client itself, because this means it would disappear if the client somehow gets recreated (in which case we do want to invalidate that condition)

**Comment by nunomaduro** [comment]
Updated the pull request with a test on this one.

I am very confident with this solution, and now I have full understanding about SSR cache hydration. 👍🏻

**Comment by francoischalifour** [comment]
@Haroenv We can track the search client in `updateClient`, which is what we're doing with user agents:

https://github.com/algolia/react-instantsearch/blob/49b46010d0a7e7494442dabc4b590e468acdfc57/packages/react-instantsearch-core/src/core/createInstantSearchManager.js#L118-L122

It's not clean to mutate external objects. We should aim at keeping our internal states local.

File: packages/react-instantsearch-core/src/core/createInstantSearchManager.js (hunk 1 above)
Comment (nunomaduro) [reply packages/react-instantsearch-core/src/core/createInstantSearchManager.js:346]: done

**Comment by francoischalifour** [comment]
@nunomaduro I don't think this conversation should be marked as resolved since I didn't get an answer: https://github.com/algolia/react-instantsearch/pull/2926#discussion_r425773897. Would you mind explaining the reasoning?

Conceptually, the `client._cacheHydrated` check should probably be right at the beginning of the `hydrateSearchClient` function so that it fully respects the flow of the code. Right now it doesn't, which makes the test not fully cover this branch:

https://github.com/algolia/react-instantsearch/blob/49b46010d0a7e7494442dabc4b590e468acdfc57/packages/react-instantsearch-core/src/core/createInstantSearchManager.js#L331-L336

**Comment by nunomaduro** [comment]
> @nunomaduro I don't think this conversation should be marked as resolved since I didn't get an answer: #2926 (comment). Would you mind explaining the reasoning?

Sorry about that. Here is the reasoning:

@francoischalifour I was just trying to make the changes just impactful for clients working with the `v4`. Putting the `if` at the begging will make the change potentially impact on `@v3` customers too.

**Comment by nunomaduro** [comment]
Well, I agree with `It's not clean to mutate external objects. We should aim at keeping our internal states local.`.

The problem is: if you keep saving local instance of objects you may face a memory leak if the customer is not reusing the same client instance every time.

**Comment by francoischalifour** [comment]
I was talking about a local boolean variable `isClientHydrated` that keeps track just like `client._isHydrated` does but remains internal.

File: examples/server-side-rendering/src/createApp.js [hunk 3]
```diff
@@ -1,13 +1,14 @@
 import algoliasearch from 'algoliasearch/lite';
+
 import App from './App';
 
+const searchClient = algoliasearch(
```
Comment (francoischalifour) [inline examples/server-side-rendering/src/createApp.js:5]: Is this change still required?

File: packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js [hunk 4]
```diff
@@ -264,6 +264,51 @@ describe('createInstantSearchManager', () => {
...
+
+      searchClient.search = 'already-overridden';
+
+      createInstantSearchManager({
+        indexName: 'index',
+        searchClient,
+        resultsState,
+      });
+
+      expect(searchClient.search).toEqual('already-overridden');
```
Comment (francoischalifour) [inline packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js:310]: Since this is a string, I believe this test doesn't actually test the new behavior. We should attach an actual function to check that the reference changes only once, right?

Comment (Haroenv) [reply packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js:310]: what we're checking is that after the search client has been "hydrated" once, it will no longer change, so if we manually change it to something we can easily check the reference of (a string), it will no longer change. Before this PR it would have changed a second time

Comment (francoischalifour) [reply packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js:310]: Gotcha! We don't make sure that reference says the same though, which is what our code does.

@nunomaduro It would make more sense to attach `jest.fn()` to `.search` and to check the function reference. Wdyt?

File: examples/server-side-rendering/src/createApp.js (hunk 3 above)
Comment (nunomaduro) [reply examples/server-side-rendering/src/createApp.js:5]: Yeah - customers usually put the algoliasearch outside of the scope of `createApp`. So it's instance can be shared between requests.

Also, the that's the way we document things.

File: packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js (hunk 4 above)
Comment (nunomaduro) [reply packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js]: Good idea.

Addressed here: https://github.com/algolia/react-instantsearch/pull/2926/commits/4c28cb98bc88f8ad1e5b2f2bb23734e25961a0f2.

**Comment by nunomaduro** [comment]
Rebased and ready to be merged.
