### PR TITLE
fix(connectRange): check if facet exist before access

### LINKED ISSUE #630: Changing the attributeName prop of a ConnectedRange results in failed request
**Do you want to request a *feature* or report a *bug*?** BUG

**Bug: What is the current behavior?**

When changing the value of the `attributeName` prop passed to a mounted component wrapped with `connectRange`, the new request fails with `ATTRIBUTE_NAME_2 is not present in 'facets' or 'disjunctiveFacets'`

Here is a simple reproduction example: https://codesandbox.io/s/ojxzzoky55

To generate the issue, switch the select tag to "Movies & TV shows"

**Bug: What is the expected behavior?**

The request doesn't fail and the ConnectedRange uses the correct `attributeName` passed down as a prop.

**What is the version you are using? Always use the latest one before opening a bug issue.** npm@latest

### PR DESCRIPTION
**Pull request by samouss**
**Summary**

Fix #630 

In the `connectRange` we need to access the stats & the values of the given facet in order to compute the range. But it may happen that the facet is not yet present on the results so we need to check that the facet is present on results before accessing it.

### CODE REVIEW

File: packages/react-instantsearch/src/connectors/connectRange.js [hunk 1]
```diff
@@ -190,8 +190,13 @@ export default createConnector({
   getProvidedProps(props, searchState, searchResults) {
     const { attributeName, precision, min: minBound, max: maxBound } = props;
     const results = getResults(searchResults, this.context);
-    const stats = results ? results.getFacetStats(attributeName) || {} : {};
-    const count = results
+    const isFacetExist = results && results.getFacetByName(attributeName);
```
Comment (Haroenv) [inline packages/react-instantsearch/src/connectors/connectRange.js]: `facetExists` seems like a better name

Comment (samouss) [reply packages/react-instantsearch/src/connectors/connectRange.js]: I prefer to prefix all the boolean value like one with `is` or `has` it make them explicit. Would you agree for `isFacetExists` ?

Comment (Haroenv) [reply packages/react-instantsearch/src/connectors/connectRange.js]: makes sense, but grammatically it reads weird. What about `hasFacet` as something which matches the pattern but also grammar?

**Comment by samouss** [comment]
@Haroenv should be good now!
