### PR TITLE
fix(SearchBox-hooks): correctly pass widget props

### LINKED ISSUE #3498: SearchBox widget does not accept queryHook prop
## 🐛 Bug description

`SearchBox` widget does not accept `queryHook` prop.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

```
import { SearchBox } from "react-instantsearch-hooks-web";
<SearchBox
  queryHook={(query, search) => search(query)}
/>
```

Check console for error: 

> Warning: React does not recognize the `queryHook` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `queryhook` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

## 💭 Expected behavior

`SearchBox` widget should accept `queryHook` prop in accordance with the docs:

https://www.algolia.com/doc/api-reference/widgets/search-box/react-hooks/#widget-param-queryhook

## Environment

- React InstantSearch Hooks version: 6.26.0
- React version: 17.0.2
- Browser: Version 102.0.5005.61 (Official Build) (arm64) 
- OS: macOS Monterey 12.0.1

### PR DESCRIPTION
**Pull request by Haroenv**
**Summary**

The prop "queryHook" is not a dom property, so shouldn't be passed to the ui component

**Result**

fixes #3498

### CODE REVIEW

**Review by FabienMotte — APPROVED** [review]

**Review by francoischalifour — APPROVED** [review]
I'd created this [JIRA task](https://algolia.atlassian.net/browse/FX-1460?atlOrigin=eyJpIjoiODBiNDc1ODM2YThmNGUzNDg5NTUwZDIzZjYxMjVkMWMiLCJwIjoiaiJ9) because we might have more of these in other components.

File: packages/react-instantsearch-hooks-web/src/widgets/SearchBox.tsx [hunk 1]
```diff
@@ -19,10 +19,11 @@ type UiProps = Pick<
 export type SearchBoxProps = Omit<SearchBoxUiComponentProps, keyof UiProps> &
   UseSearchBoxProps;
 
-export function SearchBox(props: SearchBoxProps) {
-  const { query, refine, isSearchStalled } = useSearchBox(props, {
-    $$widgetType: 'ais.searchBox',
-  });
+export function SearchBox({ queryHook, ...props }: SearchBoxProps) {
+  const { query, refine, isSearchStalled } = useSearchBox(
```
Comment (mikedavis77) [inline packages/react-instantsearch-hooks-web/src/widgets/SearchBox.tsx:23]: do you not need to pass the `props` to this hook as well as the `queryHook`?

Comment (Haroenv) [reply packages/react-instantsearch-hooks-web/src/widgets/SearchBox.tsx:23]: only the connector props are needed here
