### PR TITLE
fix(ssr): make sure metadata is available on initial render

### LINKED ISSUE #2972: CurrentRefinements widget doesn't render during ssr
**To Reproduce 🔍**

1. load https://ploxl.sse.codesandbox.io/?refinementList%5Bcategories%5D%5B0%5D=Appliances&page=1&configure%5BhitsPerPage%5D=12

https://codesandbox.io/s/crazy-wright-ploxl

This seems to happen because `metadata` is empty in any render on the server (inside `connectCurrentRefinements > getProvidedProps`)

**Expected behavior 💭**

current refinements shows in the html, like it does once the results are in

**Screenshots 🖥**

Untitled 2020-10-02 11_07_05

### PR DESCRIPTION
**Pull request by Haroenv**
**Summary**

Metadata isn't available on initial render/ server rendered page. This is because `registerWidget` is added only in componentDidMount, as well as only registering its change to instantsearchManager asynchronously (to prevent many requests if multiple widgets are added at once, which is normal on the first render).

This is preventing CurrentRefinements from rendering notably (only widget which uses metadata)

**Result**

metadata is caught using the same method as searchParameters, and injected via resultsState.

CurrentRefinements renders as expected in SSR.

fixes #2972

### CODE REVIEW

File: packages/react-instantsearch-core/src/core/createConnector.tsx [hunk 1]
```diff
@@ -113,6 +113,13 @@ export function createConnectorWithoutContext(
             this.props
           );
         }
+
+        if (isWidget) {
+          const isServer = true; // TODO: find a real value for this
```
Comment (Haroenv) [inline packages/react-instantsearch-core/src/core/createConnector.tsx:118]: this condition might be something related to `process`, but I'm not sure what bundle size impacts that will have

File: packages/react-instantsearch-dom/src/components/CurrentRefinements.js [hunk 2]
```diff
@@ -49,7 +49,7 @@ export const CurrentRefinements = ({
 const itemPropTypes = PropTypes.arrayOf(
   PropTypes.shape({
     label: PropTypes.string.isRequired,
-    value: PropTypes.func.isRequired,
+    value: PropTypes.func,
```
Comment (Haroenv) [inline packages/react-instantsearch-dom/src/components/CurrentRefinements.js:52]: initial render on client won't include `value`, since that's a function

**Comment by eunjae-lee** [comment]
The changes make sense to me, but I'm not proficient enough with react ssr to approve this PR.
I'd love to get others' eyes here.

File: packages/react-instantsearch-dom/src/core/createInstantSearchServer.js [hunk 3]
```diff
@@ -22,40 +23,43 @@ const createSearchParametersCollector = accumulator => {
   };
 };
 
-const getSearchParameters = (indexName, searchParameters) => {
-  const sharedParameters = searchParameters
-    .filter(searchParameter => !hasMultipleIndices(searchParameter.context))
+const getSearchParameters = (indexName, widgets) => {
```
Comment (samouss) [inline packages/react-instantsearch-dom/src/core/createInstantSearchServer.js:26]: The function used to only deal with `SearchParameters`.  We have introduced the computation of the metadata which doesn't make sense. We could create a dedicated function to derive the metadata from the collected values.

File: packages/react-instantsearch-dom/src/core/createInstantSearchServer.js [hunk 4]
```diff
@@ -180,5 +189,8 @@ export const findResultsState = function(App, props) {
     helper,
     sharedParameters,
     derivedParameters
-  );
+  ).then(results => {
+    results[0].metadata = metadata;
+    return results;
+  });
```
Comment (samouss) [inline packages/react-instantsearch-dom/src/core/createInstantSearchServer.js:195]: IIRC this shape is opaque for the consumer of `react-instantsearch` i.e. we are the only once that interact with the value. In that case I would use a more appropriate structure (i.e. an object) rather than assigning the value to the first element of the array.

File: packages/react-instantsearch-dom/src/components/CurrentRefinements.js (hunk 2 above)
Comment (samouss) [reply packages/react-instantsearch-dom/src/components/CurrentRefinements.js:52]: Rather than lower the validation we could assign a noop function to the metadata when we hydrate them.

File: packages/react-instantsearch-core/src/widgets/InstantSearch.tsx [hunk 5]
```diff
@@ -246,14 +248,15 @@ class InstantSearch extends Component<Props, State> {
     }
   }
 
-  onSearchParameters(getSearchParameters, context, props) {
+  onSearchParameters(getSearchParameters, context, props, getMetadata) {
```
Comment (samouss) [inline packages/react-instantsearch-core/src/widgets/InstantSearch.tsx:251]: The signature becomes a bit ugly. IMO it would be simpler to introduce a new prop/function with a simpler signature. We can then adapt the current implementation on the new one without BC. Here is an example:

```js
class InstantSearch {
  onSearchParameters(widget, context, props) {
    if (this.props.onSearchParameters) {
      this.props.onSearchParameters(widget.getSearchParameters, context, props, searchState);
    }
  }

  onFindBetterNameThanThis(widget, context, props) {
    if (this.props.onFindBetterNameThanThis) {
      this.props.onFindBetterNameThanThis(widget, context, props, searchState);
    }
  }
}
```

File: packages/react-instantsearch-dom/src/core/createInstantSearchServer.js (hunk 4 above)
Comment (Haroenv) [reply packages/react-instantsearch-dom/src/core/createInstantSearchServer.js:195]: that's an interesting option. I think I remember seeing people loop over the results since they always knew it's an array, but usually those use cases didn't really make sense to me

File: packages/react-instantsearch-core/src/widgets/InstantSearch.tsx (hunk 5 above)
Comment (Haroenv) [reply packages/react-instantsearch-core/src/widgets/InstantSearch.tsx:251]: I didn't rename it because there's a _lot_ of people who get stuck up on forgetting to pass `onSearchParameters` down to React InstantSearch, I feel like if we change it again, it might be even worse

Comment (eunjae-lee) [reply packages/react-instantsearch-core/src/widgets/InstantSearch.tsx:251]: cc @yannickcr @francoischalifour

Comment (eunjae-lee) [reply packages/react-instantsearch-core/src/widgets/InstantSearch.tsx:251]: What if we warn or throw if `onSearchParameters` is missing in the context of SSR?

Comment (Haroenv) [reply packages/react-instantsearch-core/src/widgets/InstantSearch.tsx:251]: these detections of server side rendering often cause accidental polyfills, not sure how to detect a prop is not passed only then

Comment (eunjae-lee) [reply packages/react-instantsearch-core/src/widgets/InstantSearch.tsx:251]: Hmm I didn't think of accidentail polyfills. But that snippet might be okay, because it's directly coming from the internal code of React: https://github.com/facebook/react/blob/1eb2b892dfffedfdb57039ef715fc7049f4d538a/packages/shared/ExecutionEnvironment.js
but again, I'm not too sure.

File: packages/react-instantsearch-dom/src/core/createInstantSearchServer.js [hunk 6]
```diff
@@ -150,28 +161,38 @@ export const findResultsState = function(App, props) {
...
-    <App
-      {...props}
-      onSearchParameters={createSearchParametersCollector(searchParameters)}
-    />
+    <App {...props} widgetsCollector={createWidgetsCollector(widgets)} />
   );
 
+  if (widgets.length === 0) {
+    throw new Error(
+      '[ssr]: no widgets were added, you likely did not pass the `widgetsCollector` down to the InstantSearch component.'
```
Comment (eunjae-lee) [inline packages/react-instantsearch-dom/src/core/createInstantSearchServer.js:172]: Nice. I like this 👍

File: packages/react-instantsearch-dom/src/core/createInstantSearchServer.js (hunk 4 above)
Comment (Haroenv) [reply packages/react-instantsearch-dom/src/core/createInstantSearchServer.js:207]: https://github.com/algolia/react-instantsearch/pull/2977 here's that alternative

File: packages/react-instantsearch-core/src/widgets/InstantSearch.tsx [hunk 7]
```diff
@@ -246,7 +256,15 @@ class InstantSearch extends Component<Props, State> {
...
 
-  onSearchParameters(getSearchParameters, context, props) {
+  onSearchParameters(
+    getSearchParameters: ConnectorDescription['getMetadata'],
+    context: {
+      ais: InstantSearchContext;
+      multiIndexContext: IndexContext;
+    },
+    props: object,
+    getMetadata?: ConnectorDescription['getMetadata']
```
Comment (eunjae-lee) [inline packages/react-instantsearch-core/src/widgets/InstantSearch.tsx:266]: I see `getMetadata` being optional here, but `widgetsCollector` is expecting it to be required.

Comment (Haroenv) [reply packages/react-instantsearch-core/src/widgets/InstantSearch.tsx:266]: good call, it's optional in both places

File: packages/react-instantsearch-dom/src/core/createInstantSearchServer.js [hunk 8]
```diff
@@ -150,28 +161,38 @@ export const findResultsState = function(App, props) {
...
 
-  const searchParameters = [];
+  const widgets = [];
 
   renderToString(
-    <App
-      {...props}
-      onSearchParameters={createSearchParametersCollector(searchParameters)}
-    />
+    <App {...props} widgetsCollector={createWidgetsCollector(widgets)} />
```
Comment (eunjae-lee) [inline packages/react-instantsearch-dom/src/core/createInstantSearchServer.js:167]: Don't forget to update [this doc](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react/) to adapt to `widgetsCollector`.

**Review by eunjae-lee — APPROVED** [review]
Looks good to me!

File: packages/react-instantsearch-dom/src/core/createInstantSearchServer.js (hunk 8 above)
Comment (Haroenv) [reply packages/react-instantsearch-dom/src/core/createInstantSearchServer.js:167]: https://github.com/algolia/doc/pull/4992

File: packages/react-instantsearch-core/src/widgets/InstantSearch.tsx (hunk 7 above)
Comment (Haroenv) [reply packages/react-instantsearch-core/src/widgets/InstantSearch.tsx]: actually ConnectorDescription already makes it optional, so this was duplicate

**Comment by ItsWendell** [comment]
@Haroenv  Great work but sadly this broke SSR in my codebase using NextJS, this should have been marked as a breaking change according to semver but is not.

Also the example should have been updated too. https://github.com/algolia/react-instantsearch/tree/master/examples/next/pages
